; This file describes fixture build properties

[fixtures]
timestamp = 2026-04-27T22:57:45.105862
build = zkevm
ref = refs/tags/tests-zkevm@v0.3.4
commit = b1d870f8f06d9eba3d74179c39660cedb98f1f38
command_line_args = fill -c /opt/actions-runner/_work/execution-specs/execution-specs/packages/testing/src/execution_testing/cli/pytest_commands/pytest_ini_files/pytest-fill.ini --rootdir . -n auto -m blockchain_test --fork=Amsterdam ./tests/ --output=fixtures_zkevm.tar.gz --build-name zkevm --no-html --durations=100 --log-level=DEBUG --ignore tests/evm_tools --ignore tests/json_loader --ignore tests/fixtures --generate-all-formats --use-pre-alloc-groups

[packages]
pytest = 8.4.2
pluggy = 1.6.0

[plugins]
json-report = 1.5.0
xdist = 3.8.0
cov = 4.1.0
html = 4.1.1
custom-report = 1.0.1
regex = 0.2.0
metadata = 3.1.1

[tools]
t8n = 2.19.0

[environment]
python = 3.13.12
platform = Linux-6.8.0-100-generic-x86_64-with-glibc2.39
ci = true

